name: CI & Release

on:
  push:
    branches: [ main ]
  pull_request:

# Füge Berechtigungen für den Workflow hinzu
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, sqlite, openssl
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests
        run: composer test

  release:
    name: Semantic Release
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npx semantic-release

  # packagist:
  #   name: Update Packagist
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs: release
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Notify Packagist
  #       run: |
  #         curl -X POST https://packagist.org/api/update-package \
  #           -d '{"repository":"https://github.com/webkult/laravel-smtp-mailing"}' \
  #           -H "Content-Type: application/json" \
  #           -H "Authorization: Bearer ${{ secrets.PACKAGIST_TOKEN }}"
